### PR TITLE
Vendored dependencies and fixed python requirements file.

### PR DESCRIPTION
**Pull request by Tri125**
This PR fixes a syntax error with the requirements file.
I also vendored ``github.com/disintegration/imaging`` to have a build that we can easily reproduce. Alternatively, don't vendor to keep the repo size small and use [dep](https://github.com/golang/dep) to lock imaging to a specific version.

### CODE REVIEW

**Comment by Tri125** [comment]
I just realized that since the main file is located under quads, that vendor should be there. This is fixed with f66.

**Comment by bradymadden97** [comment]
Can I just include Gopkg.lock and Gopkg.toml? I don't know how I feel about vendoring everything into the repo.

**Comment by Tri125** [comment]
Yes. If you use dep you can omit the vendor folder and just commit both the lock and toml file.
Anyone wanting to use your package will need to have dep and they will only have to run ``dep ensure`` to fetch your project dependency. However, not everyone use dep as it's not *yet* part of the standard toolchain.

**Comment by esimov** [comment]
@Tri125  i don't think that all of the included dependencies are necessary.  @bradymadden97 one thing i would certainly omit is to include Python only for gif generation. Go's core library already contains the gif encoder, so you can definitely use it. For reference check this out: https://github.com/esimov/stackblur-go/blob/master/cmd/main.go (definitely not to promote myself).

**Comment by bradymadden97** [comment]
Removed python gif tool. Go gif palette doesn't match colors very well so I'll have to see if there's a better way but in the meantime this will be easier to use. @esimov which dependencies do you think are unnecessary? Should I only include ones not from @golang?

**Comment by Tri125** [comment]
``github.com/disintegration/imaging`` uses ``golang.org/x/image/bmp`` and ``golang.org/x/image/tiff``. The other folders can be removed but keep the .git files and license+patent. I see that you are going ahead with the change without requesting modification to the PR so I'll let you do it directly.

**Pull request closed without merging**
